FROM node:15-alpine
WORKDIR /app

COPY . .
RUN npm install

ENV NODE_ENV=production
ENV PORT=80
ENV TOKEN=
ENV APPLICATION_CLIENT_ID=
ENV APPLICATION_CLIENT_SECRET=
ENV SESSION_SECRET=

EXPOSE 80
RUN npm run build

CMD [ "npm", "run", "serve" ]