version: '3.8'
services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: shaderBOT
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    web:
        image: niemandtv/shaderbot:0.0.1
        environment:
            PG_HOST: 'db'
        depends_on:
            - db
        ports:
            - '80:80'
