ALTER TABLE "appeal" ALTER COLUMN "userId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "appeal" ALTER COLUMN "resultModeratorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "appeal" ALTER COLUMN "resultEditModeratorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "appeal" ALTER COLUMN "messageId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "ban" ALTER COLUMN "userId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "ban" ALTER COLUMN "moderatorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "ban" ALTER COLUMN "editModeratorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "channel_lock" ALTER COLUMN "channelId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "channel_slowmode" ALTER COLUMN "channelId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "kick" ALTER COLUMN "userId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "kick" ALTER COLUMN "moderatorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "kick" ALTER COLUMN "editModeratorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "lifted_ban" ALTER COLUMN "userId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "lifted_ban" ALTER COLUMN "moderatorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "lifted_ban" ALTER COLUMN "editModeratorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "lifted_ban" ALTER COLUMN "liftedModeratorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "lifted_mute" ALTER COLUMN "userId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "lifted_mute" ALTER COLUMN "moderatorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "lifted_mute" ALTER COLUMN "editModeratorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "lifted_mute" ALTER COLUMN "liftedModeratorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "mute" ALTER COLUMN "userId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "mute" ALTER COLUMN "moderatorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "mute" ALTER COLUMN "editModeratorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "note" ALTER COLUMN "userId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "note" ALTER COLUMN "moderatorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "note" ALTER COLUMN "editModeratorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "project" ALTER COLUMN "channelId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "project" ALTER COLUMN "ownerIds" SET DATA TYPE bigint[];--> statement-breakpoint
ALTER TABLE "project" ALTER COLUMN "roleId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "project_mute" ALTER COLUMN "userId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sticky_thread" ALTER COLUMN "channelId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sticky_thread" ALTER COLUMN "threadId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "sticky_thread" ALTER COLUMN "moderatorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "track" ALTER COLUMN "userId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "track" ALTER COLUMN "moderatorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "track" ALTER COLUMN "editModeratorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "warn" ALTER COLUMN "userId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "warn" ALTER COLUMN "moderatorId" SET DATA TYPE bigint;--> statement-breakpoint
ALTER TABLE "warn" ALTER COLUMN "editModeratorId" SET DATA TYPE bigint;