version: '3.8'
services:
    db:
        restart: always
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: shaderBOT
        volumes:
            - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./pgdata:/var/lib/postgresql/data
            - ./customContent:/app/customContent
        ports:
            - '5432:5432'
    server:
        restart: always
        image: kneemund/shaderbot
        environment:
            PG_HOST: 'db'
        depends_on:
            - db
        # ports:
        #     - '80:80'
