on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Build & Push Images to GHCR

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

concurrency:
  cancel-in-progress: true
  group: publish-ghcr

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up QEMU for multi-arch
        uses: docker/setup-qemu-action@v4
      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          flavor: latest=true
      - name: Build
        id: build_image
        uses: redhat-actions/buildah-build@v3
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: ./Dockerfile
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v3
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
